[package]
name = "pokebot"
version = "0.1.0"
authors = ["Jokler <jokler@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tsclientlib = { git = "https://github.com/ReSpeak/tsclientlib" }
tsproto-packets = { git = "https://github.com/ReSpeak/tsclientlib" }
log = "0.4.8"
log4rs = "0.9"
toml = "0.5.5"
structopt = "0.2"

tokio = "0.1"
tokio-process = "0.2.4"
tokio-signal = "0.2"
# Changes enabled features on tsclientlib to fix errors on it
tokio02 = { package = "tokio", version = "0.2.0", features = ["tcp", "io-util", "sync"] }

futures01 = { package = "futures", version = "0.1.21" }
futures-preview = { version = "=0.3.0-alpha.19", features = ["compat"] }

futures-util = "0.3.1"

glib = "0.9"
gstreamer = "0.15.0"
gstreamer-app = "0.15.0"
gstreamer-audio = "0.15.0"
byte-slice-cast = "0.3.5"
serde_json = "1.0.44"
serde = "1.0.104"
