[package]
name = "pokebot"
version = "0.1.0"
authors = ["Jokler <jokler.contact@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tsclientlib = { git = "https://github.com/ReSpeak/tsclientlib/" }
tsproto-packets = { git = "https://github.com/ReSpeak/tsclientlib/" }
structopt = "0.2"
tokio = "0.1.0"
tokio2 = { package = "tokio", version = "0.2.0", features = ["tcp", "io-util"] }
futures-preview = { version = "=0.3.0-alpha.19", features = ["compat"] }
futures01 = { package = "futures", version = "0.1" }
tokio-signal = "0.2.7"
log = "0.4.8"
gstreamer = "0.15.0"
futures-util = "0.3.1"
gstreamer-app = "0.15.0"
gstreamer-audio = "0.15.0"
byte-slice-cast = "0.3.5"
serde = "1.0.104"
toml = "0.5.5"
