name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/get-package@v1
      with:
          apt-get: libgstreamer1.0-0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
