name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone pokebot
      uses: actions/checkout@v1
    - name: Download test dependencies
      uses: teddyking/dependency-action@master
      with:
          tgzDeps: https://www.archlinux.org/packages/extra/x86_64/gstreamer/download/
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
